name: Thomas_Gallagher
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3803460821509361
title: Thomas Gallagher
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74908900-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10188903333619237
  lightness: 0.812916501890868
  saturation: 0.3691431670449674
  rhythmicContrast: 0.5332952030003071
purpose: []
